# Node Types
NODE_TYPE_VISITOR = "visitor"
NODE_TYPE_PROJECT = "project"
NODE_TYPE_SKILL = "skill"
NODE_TYPE_TECHNOLOGY = "technology"
NODE_TYPE_EXPERIENCE = "experience"

# Relationship Types
REL_USES = "USES"
REL_INTERESTED_IN = "INTERESTED_IN"
REL_RELATED_TO = "RELATED_TO"
REL_HAS_SKILL = "HAS_SKILL"
REL_WORKED_ON = "WORKED_ON"
REL_DISCUSSED = "DISCUSSED"
REL_VIEWED = "VIEWED"

# Importance Levels (Ranking config weights)
IMPORTANCE_PERMANENT = 1.0
IMPORTANCE_MEDIUM = 0.6
IMPORTANCE_LOW = 0.2
